# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20171027_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(default=1, upload_to='blogapp/img'),
            preserve_default=False,
        ),
    ]
