# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='blogapp/img'),
        ),
    ]
